USE sakila;

#Challenge - Joining on multiple tables
#Write SQL queries to perform the following tasks using the Sakila database:

#1. List the number of films per category.
SELECT name AS category_name, COUNT(film_category.film_id) AS number_of_films
FROM category 
JOIN film_category 
ON category.category_id = film_category.category_id
GROUP BY category_name
ORDER BY number_of_films DESC;


#2. Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM STORE
INNER JOIN address 
USING (address_id)
INNER JOIN city
USING (city_id) #Inner join
INNER JOIN country
USING (country_id); #Inner join


#3. Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount) AS tot_rev_gen
FROM payment
INNER JOIN staff 
USING (staff_id)
INNER JOIN store
USING (store_id)
GROUP BY store.store_id;


#4. Determine the average running time of films for each category.
SELECT category.name AS name_of_category, ROUND(AVG(film.length)) AS ave_film_length
FROM film
INNER JOIN film_category
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY name_of_category;


